In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("E:/Mushrooms_classfication_project/notebook/mushrooms.csv")
df

class cap_shape cap_surface cap_color bruises odor gill_attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring_number ring_type spore_print_color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [3]:
# finding the null values in the dataset
df.isnull().sum()

class                       0
cap_shape                   0
cap_surface                 0
cap_color                   0
bruises                     0
odor                        0
gill_attachment             0
gill_spacing                0
gill_size                   0
gill_color                  0
stalk_shape                 0
stalk_root                  0
stalk_surface_above_ring    0
stalk_surface_below_ring    0
stalk_color_above_ring      0
stalk_color_below_ring      0
veil_type                   0
veil_color                  0
ring_number                 0
ring_type                   0
spore_print_color           0
population                  0
habitat                     0
dtype: int64

In [4]:
# finding the unqiue values in the dataset
df.nunique()

class                        2
cap_shape                    6
cap_surface                  4
cap_color                   10
bruises                      2
odor                         9
gill_attachment              2
gill_spacing                 2
gill_size                    2
gill_color                  12
stalk_shape                  2
stalk_root                   5
stalk_surface_above_ring     4
stalk_surface_below_ring     4
stalk_color_above_ring       9
stalk_color_below_ring       9
veil_type                    1
veil_color                   4
ring_number                  3
ring_type                    5
spore_print_color            9
population                   6
habitat                      7
dtype: int64

In [5]:
# information about the coloumns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap_shape                 8124 non-null   object
 2   cap_surface               8124 non-null   object
 3   cap_color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill_attachment           8124 non-null   object
 7   gill_spacing              8124 non-null   object
 8   gill_size                 8124 non-null   object
 9   gill_color                8124 non-null   object
 10  stalk_shape               8124 non-null   object
 11  stalk_root                8124 non-null   object
 12  stalk_surface_above_ring  8124 non-null   object
 13  stalk_surface_below_ring  8124 non-null   object
 14  stalk_color_above_ring  

In [6]:
df.columns

Index(['class', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
       'gill_attachment', 'gill_spacing', 'gill_size', 'gill_color',
       'stalk_shape', 'stalk_root', 'stalk_surface_above_ring',
       'stalk_surface_below_ring', 'stalk_color_above_ring',
       'stalk_color_below_ring', 'veil_type', 'veil_color', 'ring_number',
       'ring_type', 'spore_print_color', 'population', 'habitat'],
      dtype='object')

In [7]:
# dependent columns
X=df.iloc[:,1:]

In [8]:
X

cap_shape cap_surface cap_color bruises odor gill_attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
...        ...         ...       ...     ...  ...             ...   
8119         k           s         n       f    n               a   
8120         x           s         n       f    n               a   
8121         f           s         n       f    n               a   
8122         k           y         n       f    y               f   
8123         x           s         n       f    n               a   

     gill_spacing gill_size gill_color stalk_shape  ...  \
0               c         n          k           e  ...   
1               c         b          k           e  ...   
2               c         b          n           e  ...   
3               c         n          n           e  ...   
4               w         b          k           t  ...   
...           ...       ...        ...         ...  ...   
8119            c         b          y           e  ...   
8120            c         b          y           e  ...   
8121            c         b          n           e  ...   
8122            c         n          b           t  ...   
8123            c         b          y           e  ...   

     stalk_surface_below_ring stalk_color_above_ring stalk_color_below_ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil_type veil_color ring_number ring_type spore_print_color population  \
0            p          w           o         p                 k          s   
1            p          w           o         p                 n          n   
2            p          w           o         p                 n          n   
3            p          w           o         p                 k          s   
4            p          w           o         e                 n          a   
...        ...        ...         ...       ...               ...        ...   
8119         p          o           o         p                 b          c   
8120         p          n           o         p                 b          v   
8121         p          o           o         p                 b          c   
8122         p          w           o         e                 w          v   
8123         p          o           o         p                 o          c   

     habitat  
0          u  
1          g  
2          m  
3          u  
4          g  
...      ...  
8119       l  
8120       l  
8121       l  
8122       l  
8123       l  

[8124 rows x 22 columns]

In [9]:
# target varaiable
y=df.iloc[:,1]

In [10]:
y

0       x
1       x
2       b
3       x
4       x
       ..
8119    k
8120    x
8121    f
8122    k
8123    x
Name: cap_shape, Length: 8124, dtype: object

In [11]:
#feature engineering
from sklearn.preprocessing import LabelEncoder

#Assuming y is the target variable
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
X=pd.get_dummies(X)
X

cap_shape_b  cap_shape_c  cap_shape_f  cap_shape_k  cap_shape_s  \
0           False        False        False        False        False   
1           False        False        False        False        False   
2            True        False        False        False        False   
3           False        False        False        False        False   
4           False        False        False        False        False   
...           ...          ...          ...          ...          ...   
8119        False        False        False         True        False   
8120        False        False        False        False        False   
8121        False        False         True        False        False   
8122        False        False        False         True        False   
8123        False        False        False        False        False   

      cap_shape_x  cap_surface_f  cap_surface_g  cap_surface_s  cap_surface_y  \
0            True          False          False           True          False   
1            True          False          False           True          False   
2           False          False          False           True          False   
3            True          False          False          False           True   
4            True          False          False           True          False   
...           ...            ...            ...            ...            ...   
8119        False          False          False           True          False   
8120         True          False          False           True          False   
8121        False          False          False           True          False   
8122        False          False          False          False           True   
8123         True          False          False           True          False   

      ...  population_s  population_v  population_y  habitat_d  habitat_g  \
0     ...          True         False         False      False      False   
1     ...         False         False         False      False       True   
2     ...         False         False         False      False      False   
3     ...          True         False         False      False      False   
4     ...         False         False         False      False       True   
...   ...           ...           ...           ...        ...        ...   
8119  ...         False         False         False      False      False   
8120  ...         False          True         False      False      False   
8121  ...         False         False         False      False      False   
8122  ...         False          True         False      False      False   
8123  ...         False         False         False      False      False   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0         False      False      False       True      False  
1         False      False      False      False      False  
2         False       True      False      False      False  
3         False      False      False       True      False  
4         False      False      False      False      False  
...         ...        ...        ...        ...        ...  
8119       True      False      False      False      False  
8120       True      False      False      False      False  
8121       True      False      False      False      False  
8122       True      False      False      False      False  
8123       True      False      False      False      False  

[8124 rows x 117 columns]

In [13]:
# spliting the dataset for training and testing
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=40)

In [14]:
X_train

cap_shape_b  cap_shape_c  cap_shape_f  cap_shape_k  cap_shape_s  \
7478        False        False        False         True        False   
1473        False        False         True        False        False   
2028        False        False        False        False        False   
6254        False        False         True        False        False   
7858        False        False        False        False        False   
...           ...          ...          ...          ...          ...   
3064        False        False        False        False        False   
6309        False        False         True        False        False   
6151        False        False         True        False        False   
6363        False        False         True        False        False   
3398        False        False        False        False        False   

      cap_shape_x  cap_surface_f  cap_surface_g  cap_surface_s  cap_surface_y  \
7478        False          False          False           True          False   
1473        False           True          False          False          False   
2028         True          False          False           True          False   
6254        False          False          False          False           True   
7858         True           True          False          False          False   
...           ...            ...            ...            ...            ...   
3064         True          False          False          False           True   
6309        False          False          False           True          False   
6151        False          False          False           True          False   
6363        False          False          False          False           True   
3398         True          False          False          False           True   

      ...  population_s  population_v  population_y  habitat_d  habitat_g  \
7478  ...         False          True         False       True      False   
1473  ...          True         False         False      False       True   
2028  ...         False         False         False      False       True   
6254  ...         False          True         False       True      False   
7858  ...         False         False         False      False       True   
...   ...           ...           ...           ...        ...        ...   
3064  ...         False         False          True      False      False   
6309  ...         False          True         False      False      False   
6151  ...         False          True         False       True      False   
6363  ...         False          True         False       True      False   
3398  ...         False          True         False       True      False   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
7478      False      False      False      False      False  
1473      False      False      False      False      False  
2028      False      False      False      False      False  
6254      False      False      False      False      False  
7858      False      False      False      False      False  
...         ...        ...        ...        ...        ...  
3064      False      False       True      False      False  
6309      False      False       True      False      False  
6151      False      False      False      False      False  
6363      False      False      False      False      False  
3398      False      False      False      False      False  

[5686 rows x 117 columns]

In [15]:
# all models in one code
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
import warnings

# Define the evaluation function
def evaluate_model(true, predicted):
    cm = confusion_matrix(true, predicted)
    classification_reports = classification_report(true, predicted)
    acc_score = accuracy_score(true, predicted)  # Rename the variable here

    return cm, classification_reports, acc_score



# Define the models
models = {
    "Logistic Regression": LogisticRegression(C=0.001, penalty='l2', solver='liblinear'),
    "SVM Classifier": svm.SVC(kernel='linear', C=0.0001),
    "Decision Tree": DecisionTreeClassifier(criterion='entropy', max_depth=1, min_samples_leaf=5),
    "Random Forest Classifier": RandomForestClassifier(n_estimators=50, max_depth=1, min_samples_leaf=5),
    "Gradient Boosting Classifier": GradientBoostingClassifier(n_estimators=15, max_depth=1, min_samples_leaf=3, learning_rate=0.1),
    "AdaBoost Classifier": AdaBoostClassifier(n_estimators=2, learning_rate=1.0, algorithm='SAMME')

}

# Iterate over the models
for name, model in models.items():
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    cm_train, cr_train, as_train = evaluate_model(y_train, y_train_pred)
    cm_test, cr_test, as_test = evaluate_model(y_test, y_test_pred)

    print(name)

    print('Model performance for Training set')
    print("- Confusion Matrix:\n", cm_train)
    print("- Classification Report:\n", cr_train)
    print("- Accuracy Score: {:.4f}".format(as_train))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Confusion Matrix:\n", cm_test)
    print("- Classification Report:\n", cr_test)
    print("- Accuracy Score: {:.4f}".format(as_test))
    print('\n')

e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(resu

Logistic Regression
Model performance for Training set
- Confusion Matrix:
 [[   0    0    1    0    0  325]
 [   0    0    0    0    0    2]
 [   0    0 2230    0    0    0]
 [   0    0   34  338    0  185]
 [   0    0    0    0    0   18]
 [   0    0    0    0    0 2553]]
- Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       326
           1       0.00      0.00      0.00         2
           2       0.98      1.00      0.99      2230
           3       1.00      0.61      0.76       557
           4       0.00      0.00      0.00        18
           5       0.83      1.00      0.91      2553

    accuracy                           0.90      5686
   macro avg       0.47      0.43      0.44      5686
weighted avg       0.86      0.90      0.87      5686

- Accuracy Score: 0.9006
----------------------------------
Model performance for Test set
- Confusion Matrix:
 [[   0    0    0    0    0  126]
 [   0    0

e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(resu

SVM Classifier
Model performance for Training set
- Confusion Matrix:
 [[   0    0    0    0    0  326]
 [   0    0    0    0    0    2]
 [   0    0    0    0    0 2230]
 [   0    0    0    0    0  557]
 [   0    0    0    0    0   18]
 [   0    0    0    0    0 2553]]
- Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       326
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00      2230
           3       0.00      0.00      0.00       557
           4       0.00      0.00      0.00        18
           5       0.45      1.00      0.62      2553

    accuracy                           0.45      5686
   macro avg       0.07      0.17      0.10      5686
weighted avg       0.20      0.45      0.28      5686

- Accuracy Score: 0.4490
----------------------------------
Model performance for Test set
- Confusion Matrix:
 [[   0    0    0    0    0  126]
 [   0    0    0

e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(resu

Random Forest Classifier
Model performance for Training set
- Confusion Matrix:
 [[   0    0  117    0    0  209]
 [   0    0    2    0    0    0]
 [   0    0 2230    0    0    0]
 [   0    0  530    0    0   27]
 [   0    0   18    0    0    0]
 [   0    0    0    0    0 2553]]
- Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       326
           1       0.00      0.00      0.00         2
           2       0.77      1.00      0.87      2230
           3       0.00      0.00      0.00       557
           4       0.00      0.00      0.00        18
           5       0.92      1.00      0.96      2553

    accuracy                           0.84      5686
   macro avg       0.28      0.33      0.30      5686
weighted avg       0.71      0.84      0.77      5686

- Accuracy Score: 0.8412
----------------------------------
Model performance for Test set
- Confusion Matrix:
 [[   0    0   45    0    0   81]
 [   0

e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Mushrooms_classfication_project\venv\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(resu